### PR TITLE
Add Availability Page to Dashboard

### PR DESCRIPTION
**Pull request by sophiagal**
weird error when pushing tests and need to update alert but everything works

### CODE REVIEW

**Review by ivancuadra869 — DISMISSED** [review]
Looks good!

**Review by mtahery20 — DISMISSED** [review]
Looks great! One suggestion though would be to change the font style of the "Availability" header so that it matches our other pages? Not a big deal though in my opinion, it's working perfectly!

**Review by navarrojandg — DISMISSED** [review]
Strictly looking at the code -- looks good to me

**Review by mtahery20 — APPROVED** [review]
Looks great

**Pull request merged**
