### PR TITLE
KSP-212 Authorize event-plan create, delete and update routes

### PR DESCRIPTION
**Pull request by navarrojandg**

### CODE REVIEW

**Comment by navarrojandg** [comment]
Authorize event-plans/create
Authorize event-plans/delete
Create and authorize event-plans/delete-invitees
Create and authorize event-plans/update
Create and authorize event-plans/update-invitees

@ivancuadra869 Can you deploy and test the functionality around creating and deleting event-plans please? The other new routes aren't currently wired up to any web component and would need to be wired up.

**Comment by ivancuadra869** [comment]
Event-Plan deletion completely works. 

Event-Plan creation partially works: The event-plan get's created for both the host and invitees, but there is an uncaught promise coming from the api.post in the CreateEventPlanForm.tsx

**Comment by navarrojandg** [comment]
Shouldn't need to redeploy unless you rolled back from staging but fixed the error you found

**Review by ivancuadra869 — APPROVED** [review]
Looks good. Only tested for event-plan creation and deletion. I gave the update/delete-invitees a look and it also looks good.

**Pull request merged**
