### PR TITLE
Ksp 219 merge web and web 2

### PR DESCRIPTION
**Pull request by ivancuadra869**

### CODE REVIEW

**Review by mtahery20 — CHANGES_REQUESTED** [review]
-"Finalize Event" button not working when confirming an event
-Bugs/Glitches on 'Plan an Event' page
-logo looks small and blurry

**Review by jesc0bar — COMMENTED** [review]
Plan An Event page styling for Time is broken.

Responsive for Event Plan Details looks a little off.

Finalized Event Page looks like it needs to be updated.

Overall looks fine.

**Comment by ivancuadra869** [comment]
> Plan An Event page styling for Time is broken.
> 
> Responsive for Event Plan Details looks a little off.
> 
> Finalized Event Page looks like it needs to be updated.
> 
> Overall looks fine.

Did someone update the Finalized Event Page?

**Comment by ivancuadra869** [comment]
> -"Finalize Event" button not working when confirming an event -Bugs/Glitches on 'Plan an Event' page -logo looks small and blurry

Where does the logo look small and blurry?

**Review by mtahery20 — APPROVED** [review]
Everything is functioning perfectly! Great job!

**Pull request merged**
