### PR TITLE
Add event guests update functionality

### PR DESCRIPTION
**Pull request by ivancuadra869**
For now, the update guests button removes guests that have declined.

### CODE REVIEW

**Review by navarrojandg — APPROVED** [review]
Particularly for api file names are named using kebab-case while function and variable names use camelCase and _hungarian notation for non exported / internal functions. Best practice to standardize naming schemes, will prolly update the README to reflect this.

Other than that nice job!

**Comment by navarrojandg** [comment]
Did you smoke test this Ivan? Like roughly make sure this works? Want to merge if you feel its ready because its blocking my other ticket regarding authorizing api calls.

**Comment by ivancuadra869** [comment]
Yes, i thoroughly tested it

**Comment by navarrojandg** [comment]
Do you have a corresponding jira ticket for this pr? If not you should make one to give yourself credit. Merging now.

**Pull request merged**
