### PR TITLE
Update Header Styling for Password Reset

### PR DESCRIPTION
**Pull request by mtahery20**
Couldn't figure out how to delete the year from the heatmap. I know it's on AvailabilityHeatMap.tsx between lines 25-56 but I can't figure out where I can edit it. If anyone else can figure it out I'd be super appreciative. For this PR I only changed the header on the Password Reset Page when logged out so that it matched our other headers.

### CODE REVIEW

**Review by navarrojandg — DISMISSED** [review]
If just styling -- seems good to me and okay to merge

**Review by ameliaabou — DISMISSED** [review]
Looks great!

**Comment by navarrojandg** [comment]
Rebased from staging

**Review by navarrojandg — APPROVED** [review]
Looks good to me!

**Pull request merged**
